package com.example.dummyapp.domain.model.entities.remote.homemain

data class Banner(
    val __v: Int? = 0,
    val _id: String? = "",
    val banner_color: String? = "",
    val banner_text: String? = "",
    val banner_title: String? = "",
    val banner_type: Int? = 0,
    val city_id: String? = "",
    val close: Boolean? = false,
    val created_at: String? = "",
    val days: List<String?>? = listOf(),
    val end_time: String? = "",
    val image_url: String? = "",
    val is_alsaree3_essential: Boolean? = false,
    val is_banner_visible: Boolean? = false,
    val is_current_open_order: Boolean? = false,
    val is_default: Boolean? = false,
    val is_golden_customer_banner: Boolean? = false,
    val is_in_zone: Boolean? = false,
    val is_push_notification: Boolean? = false,
    val is_qcomm: Boolean? = false,
    val is_store_list: Boolean? = false,
    val partner_id: Any? = Any(),
    val promo_code: String? = "",
    val push_zones: List<String?>? = listOf(),
    val sequence_number: Int? = 0,
    val start_time: String? = "",
    val store_id: String? = "",
    val store_list_id: String? = "",
    val unique_id: Int? = 0,
    val updated_at: String? = ""
)